# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1k7NccI0xXHiAVALIueEwdNP2jzXPPwMy
"""

# String Concatenation

string1 = "Hello "

name = input("Enter your Name: ")
string2 = string1 + name

print(string2)

string3 = ", welcome to Python programming"

final_string = string2 + string3
print(final_string)

# String Slicing and Indexing

string = "Hello Vijay, welcome to Python programming"

#  first character
print("First character:", string[0])

#  last character
print("Last character:", string[-1])

#  first 5 characters
print("First 5 characters:", string[:5])

# last 11 characters
print("Last 11 characters:", string[-11:])

#  string in reverse
print("Reverse string:", string[::-1])

#  word Python
print("Word Python:", string[24:30])

# 3. String Methods

str = "Python beginner tutorial"

#  uppercase
print("Uppercase:", str.upper())

#  lowercase
print("Lowercase:", str.lower())

# Capitalize
print("Capitalized:", str.capitalize())

#  Count of character 't'
print("Count of 't':", str.count('t'))

# Replace
print(
    "Replaced:",
    str.replace("Python", "Machine Learning")
)

#  Tuples
tuple1 = (10, 20, 30)
tuple2 = (40, 50, 60)

# Concatenate
t_combine = tuple1 + tuple2
print("Combined tuple:", t_combine)

# Repeat t_combine 3 times
t_repeat = t_combine * 3
print("Repeated tuple:", t_repeat)

#  3rd element
print("3rd element:", t_combine[2])

#  first three elements
print("First three elements:", t_combine[:3])

# last three elements
print("Last three elements:", t_combine[-3:])